### PR TITLE
Status Update Form Take 3

### PR DESCRIPTION
**Pull request by emcoding**
Moving form back into index, instead of #22 (moving index listing to new form page).
It works, as Nathan expected; it turns out it _does_ need to pass the url into the simple form arguments.

Working on some finetuning. To be continued.

### CODE REVIEW

**Comment by emcoding** [comment]
This works! 
Two questions:
1) By removing the `#new` action, I also lost the validation messages. (Which I don't understand, because validations are not called by new?) How to solve that?
2) I added an `:except` parameter to the `:resources` in `routes.rb`, is that really necessary? 

@nathanvda Back to you :-)

**Comment by nathanvda** [comment]
So, the validations are shown on the the instance variable `@status_update`. When the save fails, because of validation errors, the `simple_form_for` uses the the errors on `@status_update` to render it appropriately. E.g. you can inspect `@status_update.errors` in the rails or debug console to see what it contains on validation error. 

There are several options to choose from. So your form posts to `create`, it tries to save and then you can:

1) upon validation, instead of redirecting, just `render :index`. It will render the form with the correct instance variable. You will have to set `@status_updates` as well. 
2) upon validation error, `render :new` instead. So if there is a validation error, you render a page with only the form, which will show the appropriate error/validation messages. You will have to re-introduce the `new.html.slim` view. 
3) add `remote: true` to your form, and in `create.js.slim` you either re-render the list of items (if validation was succesful) or only re-render the form (if validation failed).

For now I think 1) or 2) is the easiest.

**Comment by emcoding** [comment]
I liked nr 1 best. I made a helper method to set the @status_updates in a DRY way. The error message is glorious as it should be :-)
I am keen to find out what you think about it.

**Comment by nathanvda** [comment]
Verrry nice :+1: Great work! 

Now instead of defining it as a helper_method, I would define it as a `before_action :get_status_updates, only: [:index, :create]` and use the instance variable in the views. I prefer that because 1) retrieving the data is still more a controller responsibility, and we know the two places where we need to fetch the status-updates, and 2) I prefer to keep helper-methods do to something more view-related if there is a choice. But this is definitely entering a gray area, where as a developer you have different options to choose from to reach the same result. This is already awesome work! :+1: :+1: :+1: :heart_eyes:

**Comment by emcoding** [comment]
Thanks Natan! I did the helper_method, because it looks to me like another situation where I was asked to move the `before_action` into a helper method :-) But there is a big chance that I am confusing things. 
But if I am not confusing things, I am confident I could justify my choice for helper_methods over before_action here. Haha. Which I take as a sign that I am finally start to understand what I am doing...  Either way, I am happy with this solution, thanks a lot for your help.

BTW Is it okay by you if I put it now, as is, in a Pull Request to Upstream?

**Comment by nathanvda** [comment]
Of course I have no idea what the "other situation" was, so I am interested to hear more, and/or what your justification is to use a helper_method over a before_action. I am always open for good reasoning.

**Comment by emcoding** [comment]
Haha, let me try. Well, I think:
- a helper_method seems easier to maintain (and read)
- I think, not sure, that the helper_method is better for lazy init and/or:
- I think, not sure, that the helper will be called only when it's return value is needed, and not just because the action is called (say, if the var is only needed in a IF statement == true)
- It looks more beautiful. And code is poetry, right, so that matters as well ;-)

**Comment by nathanvda** [comment]
Nice! Good arguments :smile: :+1: 
- in this example, with regards to maintenance, i think using the before_action or helper method is a tie
- definitely: a helper-method is better for lazy init, but in this case we do not need the lazy init, we always want to show the list of status-updates
- also here: it will always be called imho 
- this, obviously, is a matter of taste ;) Using an instance variable in a view makes it clear to me where it will be set (in the controller), using a helper-method less so. 

Thank you for explaining that, great arguments, it boils down to personal taste. This is your code, so you do it however you like :+1: :+1:

**Comment by emcoding** [comment]
:bow:

**Pull request merged**
