### PR TITLE
Improve activities feed view #259

### PR DESCRIPTION
**Pull request by roosdebildt**
Improves look and view of activity feed, fixes the size of images in the updates.

Like this:
screen shot 2015-07-12 at 17 28 43

### CODE REVIEW

**Comment by roosdebildt** [comment]
@carpodaster and @alicetragedy could you review if it's ready for merging :)?

**Comment by alicetragedy** [comment]
@roosdebildt I can take a look tonight – if @carpodaster can review before, that's okay for me too ;)

**Comment by carpodaster** [comment]
It's CSS, so I'm more like …



:wink:

**Comment by roosdebildt** [comment]
Hahahaha, fair enough!

**Comment by alicetragedy** [comment]
@carpodaster okay, then I'm happy to ;)

css 2

**Comment by carpodaster** [comment]
@alicetragedy I hope by the time I die, they have tombstones with embeded flatscreens. BECAUSE THAT GIF SHALL BECOME MY EPIPATH!

**Comment by roosdebildt** [comment]
WHY CAN'T I EMBED GIPHIES IN MY COMMENTS. I'm so upset.

**Comment by alicetragedy** [comment]
@roosdebildt you should be able to drop your gif right into the text field... or do you mean you want to use /giphy like in slack? ;)
@carpodaster :computer: :skull:

**Comment by emcoding** [comment]
http://www.digizerk.eu/index.php?option=com_content&task=view&id=21&Itemid=37

**Comment by roosdebildt** [comment]
I just get this:


:'(

**Comment by yorickpeterse** [comment]
You'll need to actually link to an image:

no way

**Comment by alicetragedy** [comment]
Hi @roosdebildt, could you do the pull request against the `rails-girls-summer-of-code/rgsoc-teams repo` (master branch)? I know that you are doing internal PRs with your coaches and I think it's a good workflow, but in this case (with css that will need looking at in the browser) it would be easier for me to fetch your changes and review your pull request if it's done against "our" master branch. let me know if you need any help!

**Comment by roosdebildt** [comment]
> "You'll need to actually link to an image"

@YorickPeterse:

**Pull request merged**
